### ISSUE TITLE
Refreshing post gives 404 not found

### ISSUE THREAD

**Issue by tbranyen** [rajaraodv/react-redux-blog#1]
Reproduce: Click demo link in the README, click on a post (I choose the first one), hit refresh.
Expected: To see the post
Actual: Not found

**Comment by rajaraodv** [comment]
Thanks @tbranyen! I had to fix the Express' routes 😀

**Comment by tbranyen** [comment]
:+1:

**Comment by peter-mouland** [comment]
this is still a problem with the demo on heroku
