### ISSUE TITLE
Showing error on installing the dependencies

### ISSUE THREAD

**Issue by mglrahul** [rajaraodv/react-redux-blog#10]
Hi rajaraodv, thanks for providing us a such as a nice app, which we can study and learn the redux app with mongodb support, I search the web but couldn't found a good example like this. i learned a lot from you, Please help me in this app.

i have downloaded the repo but when i try to install the dependencies, i got the following error. If you have some time, please take a look. thanks in advance

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\react-redux-blog\npm-debug.log

**Comment by rajaraodv** [comment]
Looks like windows related issue. Sorry, not sure how to help here.

**Comment by mglrahul** [comment]
ok, thanks
