### ISSUE TITLE
Question about return from signInUser action to dispatch in signInUserContainer

### ISSUE THREAD

**Issue by marcogonzalo** [rajaraodv/react-redux-blog#4]
I'm obtaining a Promise from axios.post() in request on UserAction, that is asigned to payload attribute at `return { type: SIGNIN_USER, payload: request }`, but at dispatch I can't use this promise with .then(), Why you can do this? I had to do this: 
`
let response = dispatch(signInUser(values)); 
response.payload.then();
`
What is the difference in your code?

If you are interested, I have posted a [question in StackOverflow about it](http://stackoverflow.com/questions/36230843/dispatch-calls-a-function-but-then-doesnt-work-on-react-redux), but I haven't received answers.

**Comment by rajaraodv** [comment]
Answered it on stackoverflow.
