### ISSUE TITLE
INITIAL_STATE loading prop

### ISSUE THREAD

**Issue by itaylorweb** [rajaraodv/react-redux-blog#5]
Hi.  Should the INITIAL_STATE loading prop not be set to true and only set to false on either FETCH_POSTS_SUCCESS or FETCH_POST_FAILURE?

The loading prop currently is only set to true once the axios promise is resolved due to using the redux-promise middleware.  If the initial value of loading is set to true then as soon as the request is initiated loading is true.

Just an observation.

**Comment by rajaraodv** [comment]
No. Because if it's set to true then we'll show "loading" in the app.
