### ISSUE TITLE
ROOT_URL constant

### ISSUE THREAD

**Issue by vernondegoede** [rajaraodv/react-redux-blog#8]
First of all, thank you for your great posts on Medium explaining Redux step by step! Really helped me understand the basics of Redux.

I was going through your code in this repo and saw the `ROOT_URL` constant a few times. I was wondering why you're checking wether the `ROOT_URL` includes localhost or not. What's the advantage of using relative paths when running the app on localhost?

This is not an issue but more a question  in general :)

**Comment by rajaraodv** [comment]
When we are running on Heroku, we'll have the client and the server on the same port. But on localhost, we are running node server on port 3000 but are running dev-server on port 8080. So on Heroku, we are simply using /api and using http://localhost:3000/api on the localhost.

`const ROOT_URL = location.href.indexOf('localhost') > 0 ? 'http://localhost:3000/api' : '/api';
`
