### ISSUE TITLE
Token is always undefined?

### ISSUE THREAD

**Issue by raginrob** [rajaraodv/react-redux-blog#9]
Thank you for your sample app, this is a great learning resource for me. I'm currently trying to make use of your authentication middleware in the app.js file. However, whenever I run the application, create a user and log in with that user, at no time there is a token defined after this line:

`var token = req.body.token || req.query.token || req.headers['x-access-token'];
 console.log('Token: ', token); // <--- always gives me 'Token: undefined'`

The login process runs just as expected, the user gets created in mongo and everything looks fine, except for the empty token. It does not matter if I run the production version or the dev version on 8080, I also tried it with Firefox and Opera (on Linux).

Is this an error that is caused by my environment or can you confirm this behaviour? I have been fiddling around with this for some hours now, but it seems I'm too unexperienced with that for now.

Bestr regards,
Rob

**Comment by rajaraodv** [comment]
That specific code was to deal w/ verifying email where the the user clicks on a link that contains jwt-token. Anyway, I am working on an updated code to make it more simple. Will check it in soon.
